[project]
name = "python-antsy"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 130
disable = "missing-class-docstring, missing-function-docstring, trailing-whitespace, no-member"

[tool.ruff]
line-length = 130
ignore = ["E402"]
